name: Release to NuGet and GitHub Packages

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./src
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release
      
      # Push to GitHub Packages
    - name: Auth to GitHub Packages
      run: dotnet nuget add source "https://nuget.pkg.github.com/SergeyGolovenchik/index.json" --name github --username SergeyGolovenchik --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
    - name: Push to GitHub Packages
      run: dotnet nuget push "**/*.nupkg" --api-key ${{secrets.GH_PACK_TOKEN}} --source "github"

      # Push to Nuget Packages
    - name: Push to NuGet
      run: dotnet nuget push "**/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
